### PR TITLE
Setup basic gui

### PR DESCRIPTION
**Pull request by knsjerome**

### CODE REVIEW

**Comment by knsjerome** [comment]
basic_gui

**Comment by knsjerome** [comment]
This PR gets rid of the boilerplate code from the Vue quick-start command. I've added a serviceable starting point for further GUI development.

**Comment by drowsell** [comment]
I'm still getting this default page. I think I am doing the wrong commands? 
I've tried: 

- npm run serve
- npm run build
- npm install -g serve
- serve -s dist

Here's the page I keep seeing. Can you let me know if I just have the command wrong on my end?
Screen Shot 2021-03-06 at 2 53 26 PM

**Comment by drowsell** [comment]
Solved previous comment by pulling your branch with "git fetch origin pull/15/head:test". Will leave my review now :)

**Review by drowsell — APPROVED** [review]
Working on my end. I can see your new pages. No buttons should be working at the moment correct?

**Comment by knsjerome** [comment]
> 
> 
> Working on my end. I can see your new pages. No buttons should be working at the moment correct?

Yes - no functionality has been coded yet.

**Pull request merged**
