### PR TITLE
Spell Creation/Deletion UI

### PR DESCRIPTION
**Pull request by drowsell**
Below are two images of the pages in this pull request. The pages are not connected to the backend yet, with a few exceptions:

- Character Select on Creation Page
- Character Select on Deletion Page
- Spell Select on Deletion Page (This is hard coded to character id 61 right now)

I need help figuring out how to load in the spells from a character. I need to load them after the character has been selected, but I am having a really hard time figuring this out. I am using your code for spells from the dashboard page. 

You can see the problem on **line 24 and 198 of SpellDetails.vue** . The current code wants me to fetch the character spells at created, but I cannot access the characterID at this point. That's why I temp have it fetching the first character you've added to the DB for testing.

On line 159 I have the selectedSpellIndex. This will be used or replaced when I can get the Spell Selection Dropdown working. 

@knsjerome Please leave comments if you have any ideas on how to solve the loading of the Spells after Characters. I will see them first thing in the morning.

image

image

### CODE REVIEW

**Comment by knsjerome** [comment]
I rebased this branch on top of master so you'll need to get the latest changes.

**Comment by knsjerome** [comment]
Ok, I've pushed changes to this branch which make the code functional. I'd like to heavily emphasize to **avoid copy-pasting other components' code**. As a rule of thumb, one should never copy paste a line of code they do not understand. This pattern of taking past work and pasting it into new contexts is dangerous without proper forethought and consistently causes avoidable errors.

**Comment by drowsell** [comment]
Thanks for taking a look at this Kevin. I appreciate the changes made especially with that fetchSpells method. I reviewed your changes in your commit on gitHub, and will take a closer look on my machine between classes today. 

I have to agree my foundation with Vue is super shaky! I think if I decide to use it in the future I'd like to build something very small from the ground up so I can learn the basics. I'm definitely glad you have experience with Vue!

I'll leave another comment on this PR after reviewing it on my machine.

**Comment by drowsell** [comment]
Hey @knsjerome, I reviewed the changes on my machine and they work perfectly! I tested creating and deleting spells on a few different characters and everything worked. I linked the issue to this PR, didn't realize that causes the need for a new review! Sorry about that.

**Comment by knsjerome** [comment]
> 
> 
> Hey @knsjerome, I reviewed the changes on my machine and they work perfectly! I tested creating and deleting spells on a few different characters and everything worked. I linked the issue to this PR, didn't realize that causes the need for a new review! Sorry about that.

I'm sure there are a few bug we haven't discovered yet, but this code should be good enough for now. I'll approve and merge.

**Comment by knsjerome** [comment]
> 
> 
> Thanks for taking a look at this Kevin. I appreciate the changes made especially with that fetchSpells method. I reviewed your changes in your commit on gitHub, and will take a closer look on my machine between classes today.
> 
> I have to agree my foundation with Vue is super shaky! I think if I decide to use it in the future I'd like to build something very small from the ground up so I can learn the basics. I'm definitely glad you have experience with Vue!
> 
> I'll leave another comment on this PR after reviewing it on my machine.

If you're looking for resources to learn Vue, the official website is pretty solid. YouTube channels such as "The Net Ninja" and "Brad Traversy Media" are also good.

**Review by knsjerome — APPROVED** [review]

**Pull request merged**
