### PR TITLE
Add global notification snackbar

### PR DESCRIPTION
**Pull request by knsjerome**
Added a new component for the GUI which gives user feedback via notifications. An example can be seen below:

image

### CODE REVIEW

**Comment by spacebugs** [comment]
I seem to be getting the error message to show up when creating character, even though the creation goes through successfully. Is this expected for the current PR

**Comment by knsjerome** [comment]
> 
> 
> I seem to be getting the error message to show up when creating character, even though the creation goes through successfully. Is this expected for the current PR

Can you provide evidence of this? I don't see how that is possible.

**Comment by knsjerome** [comment]
> 
> 
> > I seem to be getting the error message to show up when creating character, even though the creation goes through successfully. Is this expected for the current PR
> 
> Can you state your exact procedure?

Think I fixed it with the latest commit.

**Comment by spacebugs** [comment]
> > > I seem to be getting the error message to show up when creating character, even though the creation goes through successfully. Is this expected for the current PR
> > 
> > 
> > Can you state your exact procedure?
> 
> Think I fixed it with the latest commit.

Yep, looks like it fixed it

**Review by spacebugs — APPROVED** [review]
Looks like that fixed it

**Pull request merged**
